### ISSUE TITLE
p7zip update

### ISSUE THREAD

**Issue by jinfeihan57** [btolab/p7zip#3]
Is this repository licensed by the author of （soueceforge）[p7zip](https://sourceforge.net/projects/p7zip/)?
Or anyone can reach the author of p7zip? Please let me know.
I maintain a version of p7zip, but I can't reach the author of p7zip.
THE information of [my p7zip](https://github.com/jinfeihan57/p7zip/issues/114).

**Comment by h0tw1r3** [comment]
p7zip code is licensed LGPL. See the DOC/License.txt for complete information.
